services:
  - type: web
    name: cats-dogs-api
    runtime: python
    rootDir: project 17
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: cron
    name: cats-dogs-api-keepalive
    runtime: python
    rootDir: project 17
    buildCommand: pip install requests
    schedule: "*/10 * * * *"
    startCommand: python -c "import requests; requests.get('https://cats-dogs-api-vkit.onrender.com/health', timeout=60)"
